const SHOW_SEARCH_MODAL = "SHOW_SEARCH_MODAL";
const HIDE_SEARCH_MODAL = "HIDE_SEARCH_MODAL";
const SHOW_FRIEN_PROFILE_MODAL_MODAL = "SHOW_FRIEN_PROFILE_MODAL_MODAL";
const HIDE_FRIEN_PROFILE_MODAL_MODAL = "HIDE_FRIEN_PROFILE_MODAL_MODAL";
const IS_AUTH = "IS_AUTH";
const LOADING_AUTH = "LOADING_AUTH";
const GRT_USERINFORMATIONLOADING = "GRT_USERINFORMATIONLOADING";
const GET_USER = "GET_USER";
const GET_ROOMS = "GET_ROOMS";
const GET_ROOM_MESSAGES_AND_INFORMATION = "GET_ROOM_MESSAGES_AND_INFORMATION";
const GET_FRIENDS = "GET_FRIENDS";
const GET_FREINDSREQUESTS = "GET_FREINDSREQUESTS";
const GET_SEARCH_FRIEND = "GET_SEARCH_FRIEND";
const REMOVE_SEARCH_FRIEND = "REMOVE_SEARCH_FRIEND";
const FOCUS_SEACRCHINPUT = "FOCUS_SEACRCHINPUT";
const SHOW_FRIENDS_REQUESTS_MODAL = "SHOW_FRIENDS_REQUESTS_MODAL";
const HIDE_FRIENDS_REQUESTS_MODAL = "HIDE_FRIENDS_REQUESTS_MODAL";
const REMOVE_ROOM_INFORMATION = "REMOVE_ROOM_INFORMATION";
const MINUS_FRIEND_REQUEST_MARK = "MINUS_FRIEND_REQUEST_MARK";
const SET_NEW_FRIEND_REQUEST_MODAL = "SET_NEW_FRIEND_REQUEST_MODAL";
const ERROR_NOT_ALLOWED_TO_GET_THE_ROOM = "ERROR_NOT_ALLOWED_TO_GET_THE_ROOM";
const GET_MY_SENT_FRIEND_REQUEST = "GET_MY_SENT_FRIEND_REQUEST";
const GET_MY_NEW_SENT_FRIEND_REQUEST = "GET_MY_NEW_SENT_FRIEND_REQUEST";
const GET_USER_PROFILE = "GET_USER_PROFILE";
const GET_WINKS_COUNT = "GET_WINKS_COUNT";
const GET_TODAY_WINKS_COUNT = "GET_TODAY_WINKS_COUNT";
const HAD_WINKED_BEFORE = "HAD_WINKED_BEFORE";
const NO_WINKED_BEFORE = "NO_WINKED_BEFORE";
const NO_WINKED_SEARCH_BEFORE = "NO_WINKED_SEARCH_BEFORE";
const HAD_WINKED_SEARCH_BEFORE = "HAD_WINKED_SEARCH_BEFORE";
const SHOW_INVOKE_FRIEND_MODAL = "SHOW_INVOKE_FRIEND_MODAL";
const HIDE_INVOKE_FRIEND_MODAL = "HIDE_INVOKE_FRIEND_MODAL";

module.exports = {
    SHOW_SEARCH_MODAL,
    HIDE_SEARCH_MODAL,
    SHOW_FRIEN_PROFILE_MODAL_MODAL,
    HIDE_FRIEN_PROFILE_MODAL_MODAL,
    IS_AUTH,
    LOADING_AUTH,
    GET_ROOMS,
    GET_FRIENDS,
    GET_FREINDSREQUESTS,
    GET_USER,
    GRT_USERINFORMATIONLOADING,
    GET_SEARCH_FRIEND,
    FOCUS_SEACRCHINPUT,
    REMOVE_SEARCH_FRIEND,
    SHOW_FRIENDS_REQUESTS_MODAL,
    HIDE_FRIENDS_REQUESTS_MODAL,
    GET_ROOM_MESSAGES_AND_INFORMATION,
    REMOVE_ROOM_INFORMATION,
    MINUS_FRIEND_REQUEST_MARK,
    SET_NEW_FRIEND_REQUEST_MODAL,
    ERROR_NOT_ALLOWED_TO_GET_THE_ROOM,
    GET_MY_SENT_FRIEND_REQUEST,
    GET_MY_NEW_SENT_FRIEND_REQUEST,
    GET_USER_PROFILE,
    GET_WINKS_COUNT,
    GET_TODAY_WINKS_COUNT,
    HAD_WINKED_BEFORE,
    NO_WINKED_BEFORE,
    HAD_WINKED_SEARCH_BEFORE,
    NO_WINKED_SEARCH_BEFORE,
    SHOW_INVOKE_FRIEND_MODAL,
    HIDE_INVOKE_FRIEND_MODAL
}